# Main Host Configuration (RPI 4B Example, your device may differ. Check NixOS Configuration Reference for your device)
# Homelab EntryPoint
# NixOS-Hardware sets custom kernel for Pi and makes everything a pain.
# Don't enable it, or else you'll have to build it from source.
{ inputs, pkgs, ... }:
{
  imports = [
    inputs.nixos-hardware.nixosModules.raspberry-pi-4
    ./users.nix
    ./services.nix
    ./programs.nix
  ];

  # Override the kernel set by Nixos-hardware.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Network Configuration (NixOS Wiki)
  networking = {
    useDHCP = true;
    interfaces.end0 = {
      ipv4.addresses = [
        {
          address = "192.168.0.2";
          prefixLength = 24;
        }
      ];
    };
    defaultGateway = {
      address = "192.168.0.1";
      interface = "end0";
    };
    nameservers = [
      "1.1.1.1"
      "8.8.8.8"
    ];
  };

  # Set FileSystems and devices, point to the image's autogenerated labels
  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_SD";
    fsType = "ext4";
  };
  fileSystems."/boot/firmware" = {
    device = "/dev/disk/by-label/FIRMWARE";
    fsType = "vfat";
  };

  # ----- LOCALE -----
  console.keyMap = "us-intl";
  i18n.defaultLocale = "en_US.UTF-8";
  time.timeZone = "America/New_York";

  zramSwap.enable = true;

  # Do NOT change this after the initial installation.
  system.stateVersion = "26.11";
}
