name: "Build ISO Installer"

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main

      - name: "Build Installer ISO"
        run: |
          nix build .#iso

      - uses: actions/upload-artifact@v7
        with:
          name: 'Installer ISO'
          path: 'result/iso/*.iso'
          if-no-files-found: 'error'
